window:
  width: 750
  height: 750
  title: "Mouse Input Example"

layer:
  width: 750
  height: 650

colors:
  background: [255, 255, 255]
  circle: [0, 128, 255]
  brush_default: [0, 0, 0]

circle:
  radius: 30

brush:
  radius: 5